import type { PostWithRelations } from "@/global";

export const blogPosts: PostWithRelations[] = [
  {
    id: "clx1a2b3c4d5e6f7g8h9i0j1",
    title: "AI-Powered Marketing: The Future of Customer Engagement",
    slug: "ai-powered-marketing-future",
    excerpt:
      "Explore how artificial intelligence is revolutionizing marketing strategies and creating personalized customer experiences at scale.",
    content: "Full content about AI-powered marketing...",
    imageUrl: "/tmp/p1.jpg",
    status: "PUBLISHED",
    viewCount: 1247,
    likeCount: 89,
    createdById: "usr_123456789",
    categoryId: "1",
    author: {
      id: "usr_123456789",
      name: "Sarah Chen",
      email: "sarah.chen@example.com",
      image: "/avatars/sarah-chen.jpg",
    },
    category: {
      id: 1,
      name: "Artificial Intelligence",
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "clx2b3c4d5e6f7g8h9i0j1k2",
    title: "Building Brand Loyalty Through Social Media Storytelling",
    slug: "brand-loyalty-social-media",
    excerpt:
      "Discover the art of crafting compelling brand narratives that resonate with your audience and drive long-term loyalty.",
    content: "Full content about social media storytelling...",
    imageUrl: "/tmp/p2.jpg",
    status: "PUBLISHED",
    viewCount: 892,
    likeCount: 156,
    createdById: "usr_987654321",
    categoryId: "2",
    author: {
      id: "usr_987654321",
      name: "Marcus Rodriguez",
      email: "marcus.r@example.com",
      image: "/avatars/marcus-rodriguez.jpg",
    },
    category: {
      id: 2,
      name: "Social Media",
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "clx3c4d5e6f7g8h9i0j1k2l3",
    title: "The Rise of Voice Commerce: Optimizing for Audio Shopping",
    slug: "voice-commerce-optimization",
    excerpt:
      "Learn how voice assistants are changing the e-commerce landscape and how to optimize your business for voice commerce.",
    content: "Full content about voice commerce...",
    imageUrl: "/tmp/p3.jpg",
    status: "PUBLISHED",
    viewCount: 634,
    likeCount: 78,
    createdById: "usr_456789123",
    categoryId: "3",
    author: {
      id: "usr_456789123",
      name: "Emily Watson",
      email: "emily.watson@example.com",
      image: "/avatars/emily-watson.jpg",
    },
    category: {
      id: 3,
      name: "E-commerce",
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "clx4d5e6f7g8h9i0j1k2l3m4",
    title: "Sustainable Marketing: Connecting with Eco-Conscious Consumers",
    slug: "sustainable-marketing-eco-conscious",
    excerpt:
      "Understand how sustainability messaging can differentiate your brand and attract environmentally conscious customers.",
    content: "Full content about sustainable marketing...",
    imageUrl: "/tmp/p4.jpg",
    status: "PUBLISHED",
    viewCount: 1089,
    likeCount: 203,
    createdById: "usr_789123456",
    categoryId: "4",
    author: {
      id: "usr_789123456",
      name: "David Kim",
      email: "david.kim@example.com",
      image: "/avatars/david-kim.jpg",
    },
    category: {
      id: 4,
      name: "Sustainability",
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "clx5e6f7g8h9i0j1k2l3m4n5",
    title: "Micro-Influencer Marketing: Quality Over Quantity",
    slug: "micro-influencer-marketing",
    excerpt:
      "Why partnering with micro-influencers often delivers better ROI than celebrity endorsements and how to find the right partners.",
    content: "Full content about micro-influencer marketing...",
    imageUrl: "/tmp/p2.jpg",
    status: "PUBLISHED",
    viewCount: 756,
    likeCount: 124,
    createdById: "usr_321654987",
    categoryId: "2",
    author: {
      id: "usr_321654987",
      name: "Jessica Liu",
      email: "jessica.liu@example.com",
      image: "/avatars/jessica-liu.jpg",
    },
    category: {
      id: 2,
      name: "Social Media",
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "clx6f7g8h9i0j1k2l3m4n5o6",
    title: "The Psychology of Color in Digital Marketing",
    slug: "color-psychology-digital-marketing",
    excerpt:
      "Explore how color choices impact consumer behavior and learn to use color psychology to improve your marketing effectiveness.",
    content: "Full content about color psychology...",
    imageUrl: "/tmp/p4.jpg",
    status: "DRAFT",
    viewCount: 0,
    likeCount: 0,
    createdById: "usr_654987321",
    categoryId: "5",
    author: {
      id: "usr_654987321",
      name: "Alex Thompson",
      email: "alex.thompson@example.com",
      image: "/avatars/alex-thompson.jpg",
    },
    category: {
      id: 5,
      name: "Design",
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
