name = "tz1-blog"
compatibility_date = "2025-04-18"
compatibility_flags = ["nodejs_compat","global_fetch_strictly_public"]
main = ".open-next/worker.js"
routes = [
    { pattern = "tz1.me", custom_domain = true, zone_id = "d2ac26eb5596b4587ac1c680cbdacc7e"}
]
# minify = true

# Automatically place your workloads in an optimal location to minimize latency.
# If you are running back-end logic in a Pages Function, running it closer to your back-end infrastructure
# rather than the end user may result in better performance.
# Docs: https://developers.cloudflare.com/pages/functions/smart-placement/#smart-placement
[placement]
mode = "smart"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"



[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "blog-dev" # When you create your D1 DB, you choose the name
database_id = "992fe911-50a5-4327-b594-4a205d6790c0"

[[r2_buckets]]
binding = "NEXT_INC_CACHE_R2_BUCKET"
bucket_name = "blog"