import "@/styles/globals.css";
import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
import { TRPCReactProvider } from "@/trpc/react";
import localFont from "next/font/local";

const geistSans = localFont({
	src: [
		{
			path: "./fonts/Geist-VariableFont_wght.ttf",
			weight: "100 900", // 变量字体权重范围
			style: "normal"
		}
	],
	variable: "--font-geist-sans", // 用 CSS 变量方便在全局/ Tailwind 中使用
	display: "swap"
});

export const metadata: Metadata = {
	title: "Tz Blog",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }]
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en" className={`${geistSans.variable}`} suppressHydrationWarning>
			{/* <html lang="en" suppressHydrationWarning> */}
			<body>
				<Toaster position="top-right" />
				<TRPCReactProvider>{children}</TRPCReactProvider>
			</body>
		</html>
	);
}
