import "@/styles/globals.css";

import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";

export const metadata: Metadata = {
	title: "Tz Blog",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }]
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans"
});

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en" className={`${geist.variable}`} suppressHydrationWarning>
			<body>
				<Toaster />
				<TRPCReactProvider>{children}</TRPCReactProvider>
			</body>
		</html>
	);
}
